name: Update Mariko & Erista Guide

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-mariko:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '25.6.1'

      - name: Fetch and convert guides
        run: |
          node scripts/convert-to-vitepress.js rentry.co/mariko docs/mariko.md
          node scripts/convert-to-vitepress.js rentry.co/erista docs/erista.md
          node scripts/convert-to-vitepress.js rentry.co/mariko2 docs/mariko2.md
      - name: Check for changes
        id: diff
        run: |
          git diff --quiet docs/mariko.md docs/erista.md docs/mariko2.md && echo "changed=false" >> "$GITHUB_OUTPUT" || echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        if: steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v8.1.0
        with:
          commit-message: 'docs: update documentation md from rentry'
          title: 'docs: update mariko.md, mariko2.md and erista.md'
          body: Automated daily update of docs md
          branch: auto-update/docs
          delete-branch: true
